#!/usr/bin/env bash

mntPath="/mnt/backups"
user="tggh-backups"
backupDir="backups"


while getopts 't:m:u:p:' OPTION; do
    case "$OPTION" in
        p)
            #Password
            password="$OPTARG"
            ;;
        ?)
            echo "Invalid usage!"
            echo "backup-mount-remote-drive <-p password>"
            exit 1;
            ;;
    esac
done

if [[ -z "$password" ]]; then
    mount-remote-nas-drive -t "$backupDir" -m "$mntPath" -u "$user"
else
    mount-remote-nas-drive -t "$backupDir" -m "$mntPath" -u "$user" -p "$password"
fi
