#!/usr/bin/env bash

# Start by making sure our backup drive is mounted.
backup-mount-remote-drive
if [[ "$?" -ne 0 ]]; then
    echo ">Failed to mount backup drive. Exiting..."
    exit 1
fi

if [[ -z "$1" ]]; then
    echo ">No device name to image provided (e.g. 'sda'). Exiting..."
    exit 1
fi

remoteBackupPath='/mnt/backups'

hostname=$(hostname -s)
date=$(date '+%Y-%m-%d')
backupImageName="$hostname-$date.img"
backupSource="/dev/$1";
backupTarget="$remoteBackupPath/$backupImageName"
echo ">Beginning write of $backupSource to $remoteBackupPath as $backupImageName"
#TODO source block size just in time with 'stat /dev/'?
sudo dd bs=4096 if="$backupSource" of="$backupTarget" status=progress


