#!/usr/bin/env bash

bashDir="bash-config"
if [[ -z "$GIT_REPO_DIR" ]]; then
    # If our bashrc isn't setup, this variable might not exist.
    bashGitDir="$HOME/$bashDir"
else
    bashGitDir="$GIT_REPO_DIR/$bashDir"
fi
echo ">Moving to $bashGitDir"
cd "$bashGitDir" || (echo ">Directory $bashGitDir does not exist. Exiting..." | exit 1)

cp .bashrc "$HOME/.bashrc"
echo ">Copied .bashrc to $HOME"
cp -r .bin "$HOME/"
echo ">Copied .bin to $HOME"
customDir="$HOME/.oh-my-bash/custom"
mkdir -p "$customDir"
cp -r '.oh-my-bash/custom/themes' "$customDir"
echo ">Copied custom themes to $HOME"

echo ">Please run 'src' to access the new config"
