#!/usr/bin/env bash

bashDir="bash-config"
if [[ -z "$GIT_REPO_DIR" ]]; then
    # If our bashrc isn't setup, this variable might not exist.
    bashGitDir="$HOME/$bashDir"
else
    bashGitDir="$GIT_REPO_DIR/$bashDir"
fi
if [[ ! -d "$bashGitDir" ]]; then
    echo ">Directory "$bashGitDir" does not exist. Exiting..."
    exit 1
fi

echo ">Moving to $HOME"
cd "$HOME" || (echo ">Wtf do you mean there's no home dir..." | exit 1)

# Move all the local config to the git repo
cp .bashrc "$bashGitDir/.bashrc"
echo ">Copied .bashrc to $bashGitDir"
cp .blerc "$bashGitDir/.blerc"
echo ">Copied .blerc to $bashGitDir"
cp -r .bin "$bashGitDir/"
echo ">Copied .bin to $bashGitDir"


