#!/usr/bin/env bash

bashDir="bash-config"
bashGitDir="$GIT_REPO_DIR/$bashDir"
if [[ ! -d "$bashGitDir" ]]; then
    echo ">Directory "$bashGitDir" does not exist. Exiting..." 
    exit 1
fi

echo ">Moving to $HOME"
cd $HOME || (echo ">Wtf do you mean there's no home dir..." | exit 1)

cp .bashrc "$bashGitDir/.bashrc"
echo ">Copied .bashrc to $bashGitDir"
cp -r .bin "$bashGitDir/"
echo ">Copied .bin to $bashGitDir"
customThemeDir="$HOME/.oh-my-bash/custom/themes/"
cp -r "$customThemeDir" "$bashGitDir/.oh-my-bash/custom/"
echo ">Copied custom themes to $bashGitDir"


