#!/usr/bin/env bash

bashDir="bash-config"
if [[ -z "$GIT_REPO_DIR" ]]; then
    # If our bashrc isn't setup, this variable might not exist.
    bashGitDir="$HOME/gitRepos/$bashDir"
else
    bashGitDir="$GIT_REPO_DIR/$bashDir"
fi
echo ">Moving to $bashGitDir"
cd "$bashGitDir" || (echo ">Directory $bashGitDir does not exist. Exiting..." | exit 1)

rootUserDir="/root"
cp .bashrc "$HOME/.bashrc"
echo ">Copied .bashrc to $HOME"
sudo cp .bashrc "$rootUserDir/.bashrc"
echo ">Copied .bashrc to $rootUserDir"
cp .blerc "$HOME/.blerc"
echo ">Copied .blerc to $HOME"
sudo cp .blerc "$rootUserDir/.blerc"
echo ">Copied .blerc to $rootUserDir"
cp -r .bin "$HOME/"
echo ">Copied .bin to $HOME"
sudo cp -r .bin "$rootUserDir/"
echo ">Copied .bin to $rootUserDir"

echo ">Please run 'src' or '. ~/.bashrc' to access the new config "
