#!/usr/bin/env bash
# This file should be sourced

if [[ -z "$1" ]]; then
    echo ">No directory argument provided. Exiting..."
    exit 1;
fi

if [[ -d "$1" ]]; then
    echo ">Directory already exists. Exiting..."
    exit 1;
fi

if ! mkdir "$1"; then
    echo ">Failed to directory file. Exiting..."
    exit 1;
fi

cd "$1"
