#!/usr/bin/env bash
echo "[BEGIN] Starting dotfile export..."
if [[ -n "$GIT_REPO_DIR" ]]; then
    gitRepoDir="$GIT_REPO_DIR"
else
    gitRepoDir="$HOME/gitRepos/"
fi

# $1 - Name of git repo folder for config.
# $2 - Name of export shell script.
function config_push_to_git()
{
    configDir="$gitRepoDir/$1"
    if [[ -d "$configDir" ]]; then

        echo "[START] Exporting to $1..."
        cd "$configDir"
        git pull origin master
        if !($2); then
            echo "[ERROR] Export script error. Exiting..."
            exit 1
        fi

        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            # If we have changes, the build the commit.
            git add .
            if !(git commit); then
                echo "[CANCELLED] Git commit aborted. Exiting..."
                exit 1
            fi
        fi
        echo "[SUCCESS] Export $1 complete!"
    else
        echo "[FAILURE] $1 repo missing!"
    fi
}

config_push_to_git "bash-config" "bash-export-config-to-git"
config_push_to_git "vim-config" "vim-export-config-to-git"
config_push_to_git "zsh-config" "zsh-export-config-to-git"
config_push_to_git "git-config" "git-export-config-to-git"

echo "[FINISH] Completed dotfile export!"
