#!/usr/bin/env bash
# This command is intended run on a machine with
#  - rclone set up with a 'gdrive-remote' remote
#  - a 'GDrive-Key' gpg key

# Mount google drive share
googleDriveDir="/mnt/gdrive"
gdrive-mount-remote-drive
# Mount sync drive share
googleDriveSyncDir="/mnt/gdrive-sync"
gdrive-sync-mount-remote-drive
# Delete contents of sync drive share
cd "$googleDriveSyncDir" && sudo rm -r .

# Encrypt to drive share to sync share
cd "$googleDriveDir" || (echo ">Could not access google drive share directory. Exiting..." | exit 1)
folderTarget="google-drive"
if encrypt-dir -t "$folderTarget" -o "$googleDriveSyncDir" -k 'GDrive-Key'; then
    echo ">Directory encryption failed. Exiting..."
    exit 1
fi

# Run the sync operation on that directory to 'push' the changes
googleDriveRemoteName="gdrive-remote"
echo ">Attempting to sync $googleDriveSyncDir to $googleDriveRemoteName..."
rclone sync "$googleDriveSyncDir" "$googleDriveRemoteName":

