#!/usr/bin/env bash

while getopts 'p:' OPTION; do
    case "$OPTION" in
        p)
            #Password
            password="$OPTARG"
            ;;
        ?)
            echo "Invalid usage!"
            echo "gdrive-sync-mount-remote-drive <-p password>"
            exit 1;
            ;;
    esac
done

mntPath="/mnt/gdrive-sync"
user="tggh-google-drive"
googleDriveShare="gdrive-sync"

if [[ -z "$password" ]]; then
    mount-remote-nas-drive -t "$googleDriveShare" -m "$mntPath" -u "$user"
else
    mount-remote-nas-drive -t "$googleDriveShare" -m "$mntPath" -u "$user" -p "$password"
fi
