#!/usr/bin/env bash

gitDir="git-config"
if [[ -z "$GIT_REPO_DIR" ]]; then
    # If our bashrc isn't setup, this variable might not exist.
    gitGitDir="$HOME/$gitDir"
else
    gitGitDir="$GIT_REPO_DIR/$gitDir"
fi
echo ">Moving to $gitGitDir"
cd "$gitGitDir" || (echo ">Directory $gitGitDir does not exist. Exiting..." | exit 1)

echo ">Moving to $HOME"
cd "$HOME" || (echo ">Wtf do you mean there's no home dir..." | exit 1)

# Move all the local config to the git repo
cp .gitconfig "$gitGitDir/.gitconfig"
echo ">Copied .gitconfig to $gitGitDir"
cp .gitignore "$gitGitDir/.gitignore"
echo ">Copied .gitignore to $gitGitDir"
