#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo ">No upload target specified. Exiting..."
    exit 1
fi

if [[ "$1" != *.elf ]]; then
    echo ">Not an .elf file. Exiting..."
    exit 1
fi

if [[ ! -e "$1" ]]; then
    echo ">File does not exist. Exiting..."
    exit 1
fi

sudo openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program $1 verify reset exit"
