#!/usr/bin/env bash

vimDir="vim-config"
if [[ -z "$GIT_REPO_DIR" ]]; then
    # If our bashrc isn't setup, this variable might not exist.
    vimGitDir="$HOME/$vimDir"
else
    vimGitDir="$GIT_REPO_DIR/$vimDir"
fi
echo ">Moving to $vimGitDir"
cd "$vimGitDir" || (echo ">Directory $vimGitDir does not exist. Exiting..." | exit 1)

cp .vimrc "$HOME/.vimrc"
echo ">Copied .vimrc to $HOME"
cp -r .vim "$HOME/"
echo ">Copied .vim to $HOME"
